name: hover_magnifier
description: "Hover magnifier for Flutter web & desktop. Amazon style product zoom with edge detection and glass effect."
version: 0.0.4

homepage: https://github.com/Cisco0xf/hover_magnifier
repository: https://github.com/Cisco0xf/hover_magnifier
issue_tracker: https://github.com/Cisco0xf/hover_magnifier/issues

topics: [magnifier, hover, product-zoom, image-zoom, flutter-web]
  
platforms:
  web:
  windows:
  macos:
  linux:

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
