name: hover_magnifier
description: "A Flutter package that replicates Amazon/Noon-style product hover zoom. Displays a floating magnifier overlay on mouse hover, panning with cursor movement. Built for Flutter web and desktop."
version: 0.0.2

homepage: https://github.com/Cisco0xf/hover_magnifier
repository: https://github.com/Cisco0xf/hover_magnifier
issue_tracker: https://github.com/Cisco0xf/hover_magnifier/issues

topics: [magnifier, hover, product-zoom, image-zoom, flutter-web]
  
platforms:
  web:
  windows:
  macos:
  linux:

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
